// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCamera(arg1) {
  return window['go']['main']['App']['GetCamera'](arg1);
}

export function GetCameras() {
  return window['go']['main']['App']['GetCameras']();
}

export function SaveCamera(arg1) {
  return window['go']['main']['App']['SaveCamera'](arg1);
}

export function StartCamera(arg1) {
  return window['go']['main']['App']['StartCamera'](arg1);
}

export function StopCamera(arg1) {
  return window['go']['main']['App']['StopCamera'](arg1);
}
