// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetCamera(arg1:string):Promise<main.CameraData>;

export function GetCameras():Promise<Array<main.CameraData>>;

export function SaveCamera(arg1:main.CameraData):Promise<main.CameraData>;

export function StartCamera(arg1:string):Promise<boolean>;

export function StopCamera(arg1:string):Promise<boolean>;
